title: Joel Gustafson
description: >
  I'm a junior at MIT pursuing computer science and mathematics.

baseurl: ""
url: "http://joelgustafson.com"

author:
  fullname: Joel Gustafson
  github: joeltg
  twitter: gustafjt
  email: joelg@mit.edu
